version: '3.4'

services:
  webpacktemplate:
    image: webpacktemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - postgres
    links:
      - mongo
      - postgres
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
volumes:
  mongodata:
  pgdata:
