version: '3.4'

services:
  webpacktemplate:
    image: webpacktemplate
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    restart: always
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
volumes:
  mongodata:
  pgdata:
