version: '3.4'

services:
  webpacktemplate:
    image: webpacktemplate
    build:
      context: .
      args:
        -  REACT_APP_HOST=$REACT_APP_HOST
    environment:
      HISTORY_FILENAME: "logs/log.txt"
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongo
      TASKS_COLLECTION_NAME: tasks
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_HOST: postgres
      PG_DATABASE: postgres
      PG_PORT: 5432
    ports:
      - "80:5000"
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
      - postgres
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
volumes:
  mongodata:
  pgdata:
